// <auto-generated />
namespace Ghimire_RSS_Feed.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class enu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enu));
        
        string IMigrationMetadata.Id
        {
            get { return "202009101635312_enu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
